package config

const (
	// envs
	ENV_PRODUCTION              = "PRODUCTION"
	ENV_DEVELOPMENT             = "DEVELOPMENT"
	ENV_ENVIRONMENT             = "ENVIRONMENT"
	ENV_PORT                    = "PORT"
	ENV_MONGO_URI               = "MONGO_URI"
	ENV_MONGO_DATABASE          = "MONGO_DATABASE"
	ENV_GRAPHQL_ENDPOINT        = "GRAPHQL_ENDPOINT"
	ENV_GRAPHQL_PLAYGROUND_PASS = "GRAPHQL_PLAYGROUND_PASS"
	ENV_JWT_SESSION_SECRET      = "JWT_SESSION_SECRET"
	ENV_JWT_SESSION_EXPIRATION  = "JWT_SESSION_EXPIRATION"
)
